
###
# Base image
###
FROM node:16 as base
WORKDIR /home/node/laligabot

###
# Development
###
FROM base as develop
# NB: Only copy files that are required by 'npm install'
# The 'src' and 'server' directories will be mounted as a shared volume by docker-compose (allowing for live-reload)
COPY package.json package-lock.json ./
# Before switching to non-root user, change ownership of home
RUN chown -R node:node .
USER node
RUN npm install
COPY tsconfig.json  ./